---
engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: false
ratings:
  paths:
  - "**.rb"
  - "**.js"
  - "**.jsx"
  - "**.css"
exclude_paths:
- config/**/*
- db/**/*
